server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: project-management-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/project_management}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:kubernetes}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.projectmanagement: ${LOGGING_LEVEL_COM_PROJECTMANAGEMENT:DEBUG}
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG