apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pd-standard
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard 
reclaimPolicy: Retain
volumeBindingMode: Immediate 
allowVolumeExpansion: true