apiVersion: v1
kind: Secret
metadata:
  name: project-service-secret
  namespace: projectmanagement
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "myappuser"
  SPRING_DATASOURCE_PASSWORD: "MyAppUserPass123"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/project_management"
