apiVersion: v1
kind: ConfigMap
metadata:
  name: project-service-config
  namespace: projectmanagement
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SERVER_PORT: "8080"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_PROJECTMANAGEMENT: "DEBUG"